# Generated by Django 3.2.20 on 2023-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('produitId', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('PrixUnitaire', models.FloatField()),
                ('Quantite', models.IntegerField()),
            ],
        ),
    ]
